# Generated by Django 6.0.7 on 2026-07-16 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', '💼 Work'), ('School', '📚 School'), ('Personal', '👤 Personal'), ('Shopping', '🛒 Shopping'), ('Coding', '💻 Coding'), ('Other', '📌 Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High 🔴'), ('Medium', 'Medium 🟡'), ('Low', 'Low 🟢')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
