# Generated by Django 6.0.7 on 2026-07-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_completed_at_alter_task_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
